import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import dynamic from "next/dynamic";

const yekanBakhFont = localFont({
    src : [
        {
            path : "../public/fonts/YekanBakh-VF.ttf",
            style : "normal"
        }
    ],
    variable : "--font-yekan-bakh"
})

const Header = dynamic(() => import("@/components/header/index"),{ssr : true});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${yekanBakhFont.variable}`}
            >
                <Header />
                {children}
            </body>
        </html>
    );
}
